/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package qldb.lightweight.tutorial

import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test

internal class AppTest {
    @Test
    fun itWorks() {
        val classUnderTest = App()
        Assertions.assertNotNull("app should have a greeting", "app should have a greeting")
    }
}