/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package qldb.lightweight.tutorial;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void itWorks() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", "app should have a greeting");
    }
}
