/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package qldb.lightweight.tutorial;

import com.amazonaws.services.qldb.AmazonQLDB;
import com.amazonaws.services.qldb.AmazonQLDBClientBuilder;
import com.amazonaws.services.qldb.model.CreateLedgerRequest;
import com.amazonaws.services.qldb.model.DescribeLedgerRequest;
import com.amazonaws.services.qldb.model.LedgerState;
import com.amazonaws.services.qldb.model.PermissionsMode;

import software.amazon.qldb.PooledQldbDriver;

public class App {
	String ledgerName = "hello-qldb";

	public static void main(String[] args) throws Exception {
		new App().run();
	}

	void run() throws Exception {
		createLedger();
		
		PooledQldbDriver ledger = PooledQldbDriver.builder().withLedger(ledgerName).build();
	}

	void createLedger() throws Exception {
		AmazonQLDB qldb = AmazonQLDBClientBuilder.standard().build();
		qldb.createLedger(
				new CreateLedgerRequest().withName(ledgerName).withPermissionsMode(PermissionsMode.ALLOW_ALL));

		while (true) {
			if (LedgerState.ACTIVE.name()
					.equals(qldb.describeLedger(new DescribeLedgerRequest().withName(ledgerName)).getState()))
				return;
			Thread.sleep(1000);
		}
	}
}
