/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package qldb.lightweight.tutorial

import com.amazon.ion.IonString
import com.amazon.ion.IonStruct
import com.amazon.ion.IonValue
import com.amazon.ion.system.IonSystemBuilder
import com.amazonaws.services.qldbsession.AmazonQLDBSessionClientBuilder
import com.amazonaws.services.qldbsession.model.BadRequestException
import software.amazon.qldb.PooledQldbDriver

val ion = IonSystemBuilder.standard().build()

class App {
    var ledgerName = "sample-ledger"

    fun run() {
        val ledger = PooledQldbDriver.builder()
            .withLedger(ledgerName)
            .withSessionClientBuilder(AmazonQLDBSessionClientBuilder.standard().configure())
            .build()

        println("""

Hello and welcome to the QLDB tutorial!
 
Make sure you've already setup the necessary resources by following the README instructions in the top-level directory.
""")

        ledger.session.use {
            try {
                it.execute("create table cats")
                it.execute("create index on cats (name)")
            } catch (t: BadRequestException) {
                assert(t.message?.contains("already exists") ?: false)
            }
        }

        val cats = listOf(
            Cat("Axis", 6),
            Cat("Shadow", 5)
        )

        cats.forEach { cat ->
            ledger.session.use {
                it.execute { tx ->
                    val exists = tx.execute("select 1 from cats where name = ?",
                        listOf(ion.newString(cat.name))).singleOrNull()
                    exists ?: tx.execute("insert into cats ?", listOf(cat.toIon()))
                }
            }
        }

        val tables = ledger.session.use { it.tableNames }
        tables.forEach { table ->
            println("""
                All items in $table:
                -------------${"-".repeat(table.length)}-
            """.trimIndent())
            ledger.session.use {
                it.execute("select * from $table").forEach { v ->
                    println(v.toPrettyString())
                }
            }
            println()
        }
    }

    companion object {
        @JvmStatic
        fun main(args: Array<String>) {
            App().run()
        }
    }
}

data class Cat(
    val name: String,
    val age: Int
) {
    fun toIon() = ion.newEmptyStruct().apply {
        add("name", ion.newString(name))
        add("age", ion.newInt(age))
    }
}

private fun AmazonQLDBSessionClientBuilder.configure() = this
    .withRegion("us-west-2")
